learn-dbt:
  outputs:
    dev:
      account: xxxx.ap-south-1.aws
      client_session_keep_alive: false
      database: analytics
      password: xxxxxxx
      role: ACCOUNTADMIN
      schema: dbt
      threads: 1
      type: snowflake
      user: xxxxxxxx
      warehouse: transform_wh
  target: dev
